//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemapAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEMAPSEntities : DbContext
    {
        public DEMAPSEntities()
            : base("name=DEMAPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_comentarios_denuncias> tbl_comentarios_denuncias { get; set; }
        public virtual DbSet<tbl_denuncias> tbl_denuncias { get; set; }
        public virtual DbSet<tbl_estados_denuncias> tbl_estados_denuncias { get; set; }
        public virtual DbSet<tbl_evidencias_denuncias> tbl_evidencias_denuncias { get; set; }
        public virtual DbSet<tbl_modulos> tbl_modulos { get; set; }
        public virtual DbSet<tbl_perfiles_permisos_modulos> tbl_perfiles_permisos_modulos { get; set; }
        public virtual DbSet<tbl_perfiles_usuarios> tbl_perfiles_usuarios { get; set; }
        public virtual DbSet<tbl_seguimiento_denuncias> tbl_seguimiento_denuncias { get; set; }
        public virtual DbSet<tbl_status_denuncias> tbl_status_denuncias { get; set; }
        public virtual DbSet<tbl_tipos_productos> tbl_tipos_productos { get; set; }
        public virtual DbSet<tbl_usuarios> tbl_usuarios { get; set; }
        public virtual DbSet<View_denuncias_falladas> View_denuncias_falladas { get; set; }
        public virtual DbSet<View_denuncias_finalizadas> View_denuncias_finalizadas { get; set; }
        public virtual DbSet<View_denuncias_investigacion> View_denuncias_investigacion { get; set; }
        public virtual DbSet<View_denuncias_recibidas> View_denuncias_recibidas { get; set; }
        public virtual DbSet<View_denuncias> View_denuncias { get; set; }
        public virtual DbSet<View_seguimiento_denuncias> View_seguimiento_denuncias { get; set; }
    }
}
