//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemapAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_perfiles_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_perfiles_usuarios()
        {
            this.tbl_perfiles_permisos_modulos = new HashSet<tbl_perfiles_permisos_modulos>();
            this.tbl_usuarios = new HashSet<tbl_usuarios>();
        }
    
        public int Id { get; set; }
        public string Perfil { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<byte> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_perfiles_permisos_modulos> tbl_perfiles_permisos_modulos { get; set; }
        public virtual tbl_perfiles_usuarios tbl_perfiles_usuarios1 { get; set; }
        public virtual tbl_perfiles_usuarios tbl_perfiles_usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuarios> tbl_usuarios { get; set; }
    }
}
